version: '3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        volumes: 
            - service-certs:/etc/nginx/certs
            - service-certs:/etc/nginx/vhost.d
            - service-certs:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
            - 443:443

    nginx-proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - service-certs:/etc/nginx/certs
            - service-certs:/etc/nginx/vhost.d
            - service-certs:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment: 
            - DEFAULT_EMAIL=mail@aoe.itsatreee.com

    testsocket:
        image: aoe-websockets
        ports:
            - 8445
        environment:
            - VIRTUAL_HOST=aoe.itsatreee.com
            - LETSENCRYPT_HOST=aoe.itsatreee.com
        depends_on: 
            - nginx-proxy
            - nginx-proxy-letsencrypt
volumes:
    service-certs: