version: '3'
services:
    proxy:
        image: proxy:latest
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - testsocket

    # aoetechsocket:
    #     image: itsatreee:aoetech
    #     ports:
    #         - "8443:8443"
    testsocket:
        image: aoe-websockets:latest
        ports:
            - "8445:8445"