version: '3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        volumes: 
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
            - 443:443
        restart: always

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam:ro
            - certs:/etc/nginx/certs
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment: 
            - NGINX_PROXY_CONTAINER=nginx-proxy
            - DEBUG=true
        depends_on: 
            - nginx-proxy
        restart: always

    testsocket:
        image: aoe-websockets
        ports:
            - 8445
        environment:
            - VIRTUAL_HOST=aoe.itsatreee.com
            - LETSENCRYPT_HOST=aoe.itsatreee.com
            - VIRTUAL_PORT=8445
        depends_on: 
            - nginx-proxy
            - letsencrypt
        restart: always
volumes:
    conf:
    vhost:
    html:
    dhparam:
    certs:

networks:
    default:
        external:
            name: nginx-proxy